Closes #1251 - Reconcile the README.md TOC sections describing install between Mac, Linux, and Windows
Bears-R-Us/arkouda pull request #1252
Opened 2022-04-04 16:50 UTC by Ethan-DeBandi99

This PR (closes #1251):

I added an `INSTALL.md` file because I agreed with @mhmerrill and think that this helps with the organization and readability. The `README.md` now lists the prerequisites, but instead of detailing the installs out, it now links to `INSTALL.md`. TOC has been updated to reflect these changes.

The collapsible sections have been removed as they made it difficult to find certain elements. Additionally, all headings within the prereq install instructions is now linked to the TOC.

Linux section has been updated to indicate the instructions are specific to Ubuntu.

2022-04-05 11:40 UTC, Ethan-DeBandi99 commented on INSTALL.md
> +2. [Linux (Ubuntun)](#linux-unbuntu)
Corrected the typo

2022-04-05 11:40 UTC, Ethan-DeBandi99 commented on INSTALL.md
> +2. [Linux (Ubuntun)](#linux-unbuntu)
Corrected the typo

2022-04-05 11:40 UTC, Ethan-DeBandi99 commented on INSTALL.md
> + # Install versioneer and other required python packages if they are not included in yoru anaconda install
Corrected typo

2022-04-05 11:40 UTC, Ethan-DeBandi99 commented on INSTALL.md
> + # Install versioneer and other required python packages if they are not included in yoru anaconda install
Corrected typo

2022-04-05 11:40 UTC, Ethan-DeBandi99 commented on INSTALL.md
> + # Repeat for any missing pacakges using your package manager of choice (conda or pip)
Corrected typo

2022-04-05 11:40 UTC, Ethan-DeBandi99 commented on INSTALL.md
> + # Repeat for any missing pacakges using your package manager of choice (conda or pip)
Corrected typo

2022-04-05 16:32 UTC, mhmerrill requested changes
i am ok with this, i want to see @hokiegeek2 's CentOS7 instructions added.

2022-04-06 13:42 UTC, mhmerrill approved these changes

2022-04-06 13:42 UTC, merged