Closes #1448 - `util.py` cleanup
Bears-R-Us/arkouda pull request #1484
Opened 2022-06-07 13:17 UTC by joshmarshall1

This PR (closes #1448) 

The purpose of this issue was to cleanup, deprecate, and organize the methods in `util.py` where possible.

The only major change was moving the `most_common()` method into `GroupBy` and temporarily aliasing to the new location with a deprecation warning. The rest of the changes were small, mostly deprecation warnings, and a few places where logic was adjusted to update it to current capabilities.

2022-06-07 15:34 UTC, Ethan-DeBandi99 requested changes
This looks good overall. Small change request to get the warnings all in the same format and to match other documentation. As a note, there are a few spots as well that have `arkouda.function`, the specific comments I added say to use `ak.function`. Either is really fine, but we should make them consistent so use either all `arkouda.function` or `ak.function`.

2022-06-07 15:34 UTC, Ethan-DeBandi99 commented on arkouda/util.py
> +        " Use <GroupBy>.most_common(values) instead.",
Update this message to "Use `ak.GroupBy.most_common` instead".

2022-06-07 15:34 UTC, Ethan-DeBandi99 commented on arkouda/util.py
> +        " Use x.to_ndarray() instead.",
Update this message to "Use ak.pdarray.to_ndarray` instead".

2022-06-07 15:50 UTC, pierce314159 approved these changes
Looks good to me!

2022-06-07 15:50 UTC, pierce314159 commented on arkouda/util.py
> +from arkouda.pdarraycreation import arange, array
`array` is imported but never used

2022-06-07 16:35 UTC, jeichert60 approved these changes

2022-06-08 12:46 UTC, joshmarshall1 commented on arkouda/util.py
> +from arkouda.pdarraycreation import arange, array
Removed

2022-06-08 12:51 UTC, Ethan-DeBandi99 approved these changes

2022-06-08 16:49 UTC, pierce314159 approved these changes

2022-06-08 17:10 UTC, merged