Closes #1808 - `ak.in1d()` Runtime Errors
Bears-R-Us/arkouda pull request #1809
Opened 2022-09-27 18:26 UTC by Ethan-DeBandi99

Closes #1808 

This updates the JSON parsing to properly format JSON for server messages. The issue was that the types breaking were not in the dispatch table. However, since all of the types return true for `isinstance(obj, pdarray)`, The factory method has been updated to check if the value is a pdarray and then run the pdarray conversion.  This prevents the need for multiple entries in the dispatch table doing the same thing.

2022-09-27 18:31 UTC, reuster986 requested changes
Code looks good! Could we add a test for `ak.in1d()` with some client dtype classes, just to be safe?

2022-09-28 11:22 UTC, Ethan-DeBandi99 commented
> Code looks good! Could we add a test for `ak.in1d()` with some client dtype classes, just to be safe?

@reuster986 - I added testing for the client dtype classes listed in the issue. I also added the json parsing to the message_test for these types to ensure that the message parameters are formatted correctly.

2022-09-28 13:21 UTC, pierce314159 approved these changes
Looks good!

2022-09-28 14:05 UTC, reuster986 approved these changes
excellent!

2022-09-28 14:17 UTC, Ethan-DeBandi99 commented on tests/message_test.py
> +        self.assertEqual(size, 1)
Good catch. I lost these lines and thought I had deleted. Removed and moved the `assertEqual` with the rest of the ip testing.

2022-09-28 16:00 UTC, merged