Closes #2099: Bug in left shift by >=64 bits for int/uint
Bears-R-Us/arkouda pull request #2107
Opened 2023-02-03 12:32 UTC by jaketrookman

This PR (Closes #2099) fixes a bug when left shifting by >= 64 bits for ints and uints. Also adds testing to the Binop Operator testing file.

2023-02-03 12:44 UTC, jaketrookman commented
Need to fix CI issues and testing cases were not properly added

2023-02-07 18:55 UTC, Ethan-DeBandi99 requested changes
This looks good. According to Pierce this is also broken in `>>` can we update that here?

2023-02-07 18:58 UTC, pierce314159 commented
> This looks good. According to Pierce this is also broken in `>>` can we update that here?

yup
```chapel
var before_shift = [2**64 - 1]: uint;
writeln(before_shift);
var after_shift = before_shift >> 64;
writeln(after_shift);
```
```
% chpl PlayingAround.chpl -o playing
% ./playing
18446744073709551615
PlayingAround.chpl:4: error: halt reached - Cannot bitshift 18446744073709551615 by 64 because 64 is >= the bitwidth of uint(64)
```
 and this does not match what numpy does
 ```python
>>> n = np.array([2**64 -1, 1], dtype = np.uint64)
>>> n >> 64
array([0, 0], dtype=uint64)
```

2023-02-07 19:01 UTC, pierce314159 reviewed
Everything here looks good! Just need to add the right shift logic like ethan said

2023-02-07 20:50 UTC, pierce314159 commented on src/BinOp.chpl
> +          [(ei,ri) in zip(ea,r.a)] if ri:uint < 64 then ei = val:uint << ri:uint;
we are doing `zip(ea, r.a)` here, we should do `zip(ea, ra)`

2023-02-07 20:50 UTC, pierce314159 commented on tests/operator_tests.py
> +        np_int_array = np.array([62, 63, 64, 65], dtype=np.int64)
we should combine these tests so we don't have to duplicate the setup

2023-02-07 21:19 UTC, Ethan-DeBandi99 approved these changes
Looks good.

2023-02-07 21:26 UTC, pierce314159 approved these changes
looks good! nice work!

2023-02-07 21:47 UTC, merged