Closes #2223 - `array-create.py` Benchmark updates
Bears-R-Us/arkouda pull request #2227
Opened 2023-03-16 18:02 UTC by joshmarshall1

This PR Closes #2223 

This updates the `array-create.py` benchmark to use `pytest-benchmark`

2023-03-16 20:45 UTC, Ethan-DeBandi99 approved these changes

2023-03-17 15:31 UTC, pierce314159 requested changes

2023-03-17 15:36 UTC, joshmarshall1 commented on benchmark_v2/array_create_benchmark.py
> +    size = pytest.prob_size * cfg["numLocales"]
Fixed, good catch

2023-03-17 15:40 UTC, pierce314159 approved these changes

2023-03-17 16:29 UTC, jaketrookman approved these changes

2023-03-17 16:50 UTC, merged