Closes #2265 - Fixes `ak.DataFrame.to_parquet` with empty `Strings` Column
Bears-R-Us/arkouda pull request #2269
Opened 2023-03-21 19:36 UTC by Ethan-DeBandi99

Closes #2265 

Adds handling for when an empty `Strings` object is written to Parquet. Updates access of the `lastOffset` to default to `0` if there are no offsets. This allows the workflow to properly assign attributes in the file without hitting the index error.

Adds the same handling to Parquet workflows for `SegArray` as the same logic is used. The workflow for HDF5 is slightly different and does not require this change.

2023-03-21 19:52 UTC, pierce314159 requested changes
Do we need to do the same kinda thing in `writeMultiColParquet`? We seem to have similar logic in all the `select` cases there

https://github.com/Bears-R-Us/arkouda/blob/a1bf9e7f501be65a1840ddd1d2e0078f405b4877/src/ParquetMsg.chpl#L1298

2023-03-21 20:03 UTC, Ethan-DeBandi99 commented
> Do we need to do the same kinda thing in `writeMultiColParquet`? We seem to have similar logic in all the `select` cases there
> 
> https://github.com/Bears-R-Us/arkouda/blob/a1bf9e7f501be65a1840ddd1d2e0078f405b4877/src/ParquetMsg.chpl#L1298

Oh good catch! I will get it added to those cases as well and update.

2023-03-22 13:56 UTC, joshmarshall1 approved these changes

2023-03-22 15:53 UTC, pierce314159 approved these changes

2023-03-22 16:06 UTC, merged