Closes #2377: Add groupby aggregations that require min/max on bigint
Bears-R-Us/arkouda pull request #2378
Opened 2023-04-12 22:52 UTC by pierce314159

This PR (closes #2377) adds groupby aggregations that require min/max on bigint. I thought argmin/argmax would fall out easily but I'm running into compiler errors. Those will require a bit more digging

2023-04-14 18:46 UTC, jaketrookman approved these changes
Looks good to me

2023-04-17 20:00 UTC, Ethan-DeBandi99 requested changes
Nothing major, I just think we should adjust the `class_level_max_bits` for clarity. Otherwise, this looks good. I agree that this implementation feels safer.

2023-04-17 20:01 UTC, pierce314159 commented on src/ReductionMsg.chpl
> +    var class_lvl_max_bits = 64;
Makes sense to me! I'll get that updated

2023-04-17 20:03 UTC, Ethan-DeBandi99 approved these changes

2023-04-17 20:28 UTC, jaketrookman approved these changes
The changes look good

2023-04-18 13:22 UTC, merged