add instructions to set max per-locale CPU cores and memory
Bears-R-Us/arkouda pull request #2429
Opened 2023-05-15 10:04 UTC by hokiegeek2

Closes #2418 

This PR adds content to the README file that details how to set per-locale limits for memory and CPU cores utilized.

@21771 this is per our discussion last week

2023-05-15 15:53 UTC, Ethan-DeBandi99 approved these changes
Looks good to me!

2023-05-15 16:04 UTC, pierce314159 requested changes

2023-05-16 11:13 UTC, hokiegeek2 commented on README.md
> +````
@pierce314159 argh, okay, fixing now

2023-05-16 11:26 UTC, hokiegeek2 commented on README.md
> +````
@pierce314159 fixed! thanks for finding this error

2023-05-16 23:06 UTC, pierce314159 approved these changes

2023-05-16 23:06 UTC, pierce314159 commented on README.md
> +./akouda_server --memMax=100000000000
```suggestion
./arkouda_server --memMax=100000000000
```

2023-05-16 23:07 UTC, pierce314159 commented on README.md
> +./akouda_server --memMax=100000000000
Sorry i didn't see this until after i reviewed but we dropped an `r` in `arkouda` somehow

2023-05-17 16:42 UTC, pierce314159 approved these changes

2023-05-17 21:14 UTC, merged