Closes #2444 - SegArray with String Values Parquet Support
Bears-R-Us/arkouda pull request #2492
Opened 2023-06-08 12:57 UTC by Ethan-DeBandi99

Closes #2444 

This PR adds support for writing SegArray objects with Strings values to Parquet. 

**This does not add support for the multi-column case. That will be handled separately.**

2023-06-08 17:44 UTC, pierce314159 approved these changes
Looks good to me! Nice job on this, it seems like this required _ a lot_ of attention to detail to get the localization in `writeStrSegArrayParquet` just right

2023-06-08 17:44 UTC, pierce314159 commented on src/ParquetMsg.chpl
> +      dims[0] = locDom.size: int;
it doesn't seem like `dims` is used

2023-06-08 17:53 UTC, pierce314159 requested changes
oops sorry I approved to soon. I just pulled down and to verify correctness with gasnet and im seeing an error when running the test with 4 locales

```python
ARKOUDA_RUNNING_MODE=CLIENT python3 -m pytest tests/parquet_test.py -k "test_segarray_string"
E           AssertionError: Lists differ: ['one', 'two', 'three', 'uno', 'dos', 'tres'] != ['one', 'two', 'ne\x00tw', 'uno', 'dos', 'no\x00d']
E
E           First differing element 2:
E           'three'
E           'ne\x00tw'
E
E           - ['one', 'two', 'three', 'uno', 'dos', 'tres']
E           ?                  ^^^^                  ^^^^
E
E           + ['one', 'two', 'ne\x00tw', 'uno', 'dos', 'no\x00d']
E           ?                 ++++++ ^                  ^^^^^^^
```

2023-06-08 18:06 UTC, pierce314159 commented
With 3 locales, im actually seeing this
```
 *** Incorrect guard value: 92292502241651
arkouda_server_real(9547,0x16fb24000) malloc: *** set a breakpoint in malloc_error_break to debug
*** Caught a fatal signal (proc 1): SIGABRT(6)
```
just spoke with ethan and we agreed the right way forward is to close this and reopen when these have been addressed

2023-06-13 13:31 UTC, Ethan-DeBandi99 commented on src/ArrowFunctions.cpp
> +          int64_t segmentLength = segments[segIdx+1] - segments[segIdx];
We will not because segments is artificially padded with the total # of values as the last element.

2023-06-13 13:33 UTC, Ethan-DeBandi99 commented on src/ArrowFunctions.cpp
> +            valIdx+=offsets[offIdx] - offsets[offIdx-1];
I don't remember exactly what the issue was here, but there was a specific reason I did it this way. I can dig into it more if you would like.

2023-06-13 13:34 UTC, Ethan-DeBandi99 commented on src/ParquetMsg.chpl
> +      dims[0] = locDom.size: int;
You are right. Removed.

2023-06-13 13:36 UTC, Ethan-DeBandi99 commented
@pierce314159 - Everything is functioning properly now. Thank you for checking initially. I had a configuration issue in my environment that caused me to miss the failures. I verified that everything is good to go now. I also addressed your comments from elsewhere in the code.

2023-06-13 16:14 UTC, pierce314159 approved these changes
Looks good! I verified the test passes with a couple different number of locales

2023-06-15 13:47 UTC, jaketrookman approved these changes
Looks good

2023-06-15 15:43 UTC, merged