Closes #2550: Drop support for Chapel 1.29
Bears-R-Us/arkouda pull request #2551
Opened 2023-07-05 20:02 UTC by bmcdonald3

Now that Chapel 1.31 has been released, Chapel version 1.29 is no longer supported by Arkouda.

Closes #2550

2023-07-06 19:19 UTC, pierce314159 requested changes
The only thing I have is we should revisit the compat modules and remove any that we only had because differences of `1.29` (i.e. where the `e-130` and `gt-130` version are the same). I didn't look terribly close but I think these might be a few 
- `ArkoudaArrayCompat`
- `ArkoudaBlockCompat`
- `ArkoudaMapCompat`
- `ArkoudaRegexCompat`

2023-07-06 19:19 UTC, pierce314159 commented on Makefile
do we wanna go ahead and add stuff for `gt-131` and `e-131`? or wait until theres a need to add a compat module for that?

2023-07-07 15:26 UTC, Ethan-DeBandi99 commented
Just noting that per our SOP on updating supported Chapel versions, this should not be merged until a week after the 1.31 support is added.

2023-07-07 16:18 UTC, bmcdonald3 commented on Makefile
Sorry, I'm not sure that I'm following this, what would we add there?

2023-07-07 16:21 UTC, bmcdonald3 commented
I think we have been supporting Chapel 1.31 since the Chapel release that was on June 22nd (2 weeks ago), it just hasn't been in the CI, but we have been testing it in nightly testing.

2023-07-07 16:44 UTC, pierce314159 commented on Makefile
oh i was just saying rn we have `gt-130`, which would capture `1.31` and changes that are being made to chapel main (which will become `1.32`). So i was asking if we wanted to go ahead and change that to `e-131` and `gt-131` to differentiate between 1.31 and 1.32. We don't have any use cases for this yet i was just asking if we wanted to go ahead and update the makefile in prep for that stuff

2023-07-07 16:45 UTC, pierce314159 commented on Makefile
this is very much a question. I don't have strong feelings either way and im totally down for us to just add this when becomes necessary (i.e. there's need for a compat module because of change of API in chapel main)

2023-07-10 16:05 UTC, bmcdonald3 commented on Makefile
I think I'd be in favor of waiting on making the change to the eq-131, eq-132 dirs until that's necessary, but I did remove those extra compat files, so there shouldn't be any empty compat modules anymore.

2023-07-10 21:28 UTC, pierce314159 approved these changes

2023-07-10 21:30 UTC, pierce314159 commented on Makefile
@bmcdonald3 I noticed you didn't remove `Regex` and `File` compat modules. Does it not work to remove those even though they are the same for the `e-130` and `gt-130` versions.

2023-07-19 16:05 UTC, Ethan-DeBandi99 approved these changes

2023-07-19 16:39 UTC, merged