Fixes #2564 - SetOps Test Sporadic Failures
Bears-R-Us/arkouda pull request #2565
Opened 2023-07-12 13:12 UTC by Ethan-DeBandi99

Closes #2564

Corrects the configuration of the validation data. This was sporadic due to not every random set created having an intersection.

I validated all other testing and the configurations look correct.

2023-07-12 13:32 UTC, jaketrookman approved these changes

2023-07-12 14:45 UTC, pierce314159 requested changes

2023-07-12 14:45 UTC, pierce314159 commented on PROTO_tests/tests/setops_test.py
we chatted about this a bit offline. We think it would be smart to drop the length of the random strings generated to increase the odds of having a collision / non-empty intersection. We should also prob do this for other tests that require a non-empty intersection (in1d comes to mind)

I'd prefer `1,2` so we have some variation in length and we're not only testing things of uniform length. This should give up a sample space of something like `26**2 + 26 = 702`, so if we pick a prob_size larger than that we'd be guaranteed a collision. So if `prob_size < 1000` then set to `1000` otherwise do `prob_size`.

2023-07-13 16:35 UTC, Ethan-DeBandi99 commented on PROTO_tests/tests/setops_test.py
@pierce314159 - I updated the testing for `intersect1d` and `in1d` to use `random_strings_uniform(1, 2, size)` and added checks for if the size is `<1000` to use `1000` as our minimum size.

2023-07-13 16:43 UTC, pierce314159 approved these changes

2023-07-13 17:11 UTC, merged