Closes #2585: parquet_test.py conversion for new framework
Bears-R-Us/arkouda pull request #2586
Opened 2023-07-17 22:01 UTC by pierce314159

This PR (closes #2585) converts parquet_test to the new framework. It aims to increase coverage as well by testing more representative examples/edge cases with multiple compressions

2023-07-18 12:14 UTC, Ethan-DeBandi99 commented
Noting that issue #2567 has a PR put up (#2587) to resolve it. That PR adds testing. We will need to make sure that testing gets added here.

2023-07-18 13:19 UTC, Ethan-DeBandi99 reviewed
A few very small things to address. I want to give this a second pass after my initial look through since this testing is extremely important and there are a lot of details. Overall, this looks really good.

2023-07-18 13:19 UTC, Ethan-DeBandi99 commented on PROTO_tests/tests/io_test.py
> +            )
Can we add another note about the compression on bools here? I just don't want this to be missed down the road.

2023-07-18 13:19 UTC, Ethan-DeBandi99 commented on PROTO_tests/tests/io_test.py
> +                ],
Noting again that #2587 should allow `np.nan` to be used here.

2023-07-18 20:27 UTC, pierce314159 commented on PROTO_tests/tests/io_test.py
> +        io_util.get_directory(TestParquet.par_test_base_tmp)
yah I noticed in #2580, you just had these right under the class declaration without any function. I think that's cleaner so I can update it to do the same thing here

2023-07-19 15:44 UTC, pierce314159 commented
Converting to a draft until I can add the segarray nan test from #2587 and the io tests in #2580

2023-07-19 21:10 UTC, pierce314159 commented on PROTO_tests/tests/io_test.py
yah I'm planning on reusing them across the other test classes

2023-07-20 12:55 UTC, Ethan-DeBandi99 requested changes
One thing I noticed in a few spots is that you have specific test testing `read` and `read_parquet`. It is worth noting that ultimately, `read_parquet`, `read`, `load` and `load_all` are all using `read_parquet` to perform the reads in this case. I would suggest using the `read_parquet` in the existing tests, and add a `test_read_methods` that tests the individual methods are properly processing the components that are not related to `read_parquet`.

2023-07-20 15:19 UTC, pierce314159 commented on PROTO_tests/tests/io_test.py
> +            ]
good idea!

2023-07-20 15:23 UTC, pierce314159 commented on PROTO_tests/tests/io_test.py
> +        return [-0.0, np.finfo(np.float64).min, 2.7], [1.99], [np.inf, np.nan]
sounds good!

2023-07-20 18:33 UTC, TheOddCzar789 approved these changes

2023-07-20 18:43 UTC, Ethan-DeBandi99 approved these changes

2023-07-20 18:50 UTC, jaketrookman approved these changes

2023-07-20 18:59 UTC, merged