Closes #3068 add doc strings for numpy imports
Bears-R-Us/arkouda pull request #3077
Opened 2024-04-03 18:42 UTC by ajpotts

Closes #3068 add doc strings for numpy imports.

This commit adds scripts in the file:
pydoc/preprocess/generate_import_stubs.py
to generate .pyi stub files for imports imported in the __init__.py of a module.

It also calls this functionality from
pydoc/conf.py
to extract the doc strings for imports to `arkouda.numpy` and `arkouda.scipy`.

2024-04-15 19:27 UTC, stress-tess requested changes
Nice job!! this does not seem like it was straight forward at all! (or maybe my lack of experience with data wrangling is showing 😅 ).

The only reason I'm requesting changes is cause I think it might be a good idea to add the really long files to the `.gitignore` since they will be generated with all the other documentation with a `make doc` run. So I'd like for us to look into that a bit more but everything else looks good to me!

2024-04-16 16:53 UTC, ajpotts commented on arkouda/numpy/imports.pyi
I think this is a good idea, so long as we can build these files in the CI.  I think if they have errors they will break the code.

2024-04-16 21:32 UTC, stress-tess approved these changes
looks good to me!

2024-04-22 14:20 UTC, jaketrookman approved these changes

2024-04-22 14:42 UTC, merged