Update these operator declarations to use the operator keyword
Bears-R-Us/arkouda pull request #841
Opened 2021-06-10 16:57 UTC by lydia-duncan

Chapel 1.24 added support for declaring operator overloads with a new "operator"
keyword.  This enables operator definitions to be more easily found.
Declarations without the keyword will be deprecated starting in 1.25 (which is a
few months down the road, but I figured it would be good to address avoid the
deprecation warning as soon as possible)

Two of these could be operator methods.  I'm choosing to avoid doing that right
now for compatibility with 1.24 - there were some bugs with operator methods
remaining by the time of that release that should be resolved on master, or
shortly after a PR I have opened is merged.  In the future, we can choose to
use that functionality

`make default` and `make test` both worked

----
Signed-off-by: Lydia Duncan <lydia-duncan@users.noreply.github.com>

2021-06-10 18:45 UTC, lydia-duncan commented
I'll take a look at the arkouda_tests_linux failure, but I'm confused what I'm supposed to do about the mypy one or how my change could have caused it (since I did rebase to master beforehand)

2021-06-10 18:53 UTC, glitch commented
@lydia-duncan The `mypy` thing is not your fault.  I noticed this broke a few days ago and opened Issue#839  this morning along with a fix in PR#840 . I believe it is an upstream change which caused an issue.

2021-06-10 20:32 UTC, lydia-duncan commented
Okay, the only failure remaining is the mypy failure, so I think this is actually ready for a look!

2021-06-11 12:18 UTC, glitch approved these changes

2021-06-14 13:19 UTC, ronawho commented
This bumps the minimum Chapel version to 1.24.0, right? If so the version check in the [Makefile](https://github.com/Bears-R-Us/arkouda/blob/042d1f5780d553072f6884085c35571d7c40f35d/Makefile#L100-L110) should be updated

(Historically we have tried to keep things compatible with the last 2 major chapel releases, but I'm not sure if that's still important so I'll defer to Mike/Bill)

2021-06-14 15:06 UTC, lydia-duncan commented
> This bumps the minimum Chapel version to 1.24.0, right?

That's correct.  Running against Chapel master without this change will generate deprecation warnings for operators declared without the keyword, so it's a choice between supporting 1.23.x or having warning messages with HEAD.

If we want to ensure it works with the last two release, it might be good to have testing that locks that in - I thought the testing we run for arkouda only checked latest release and current HEAD

2021-06-16 13:04 UTC, reuster986 commented
@lydia-duncan and @ronawho sorry it's taken me so long to review! I am ok with requiring Chapel 1.24 -- all our systems are already running it for the performance improvements anyway. I think let's go ahead and update the Makefile check.

2021-06-16 13:07 UTC, reuster986 requested changes
Changes look good, just waiting on an update to the Makefile version check and possibly a rebase to pull in the fix for the mypy issue.

2021-06-18 18:27 UTC, lydia-duncan commented
Alright, the Makefile change is in, and I rebased so the mypy issue was fixed as well.  I think this is ready for another look!

2021-06-19 01:25 UTC, reuster986 approved these changes

2021-06-19 01:25 UTC, merged