Closes #822 : Adds save to hdf5 functionality for Categorical
Bears-R-Us/arkouda pull request #899
Opened 2021-08-12 17:25 UTC by glitch

Closes #822 Support writing `ak.Categorical` to HDF5

This PR implements a `save` function for `Categorical` in the same vein as `pdarray` and `Strings` save implementations.
The saved HDF5 file(s) can be read back in using the standard `ak.load_all` call.

UPDATE: The `ak.load_all` call will now detect & automatically create the Categorical object stored in HDF5.  Based on @reuster986 's feedback you can now _round trip_ a pseudo dataframe (see the unit test `categorical_test.py:testSaveAndLoadCategoricalMulti` for a full example)

i.e.
```python
df = {'pda1': ak.arange(5),
      'str1': ak.array(['one', 'two', 'three', 'two', 'one']),
      'cat1': ak.Categorical(ak.array(['a', 'b', 'c', 'b', 'a']))}
ak.save_all(df, path)
df2 = ak.load_all(path)
```
Note: I also took this opportunity to fix some white-space and documentation for functions/procs in the call chain.

Note2: This also handles multiple categorical objects stored in the same HDF5 file as well as separate pdarray and Strings objects.

2021-08-12 19:13 UTC, pierce314159 approved these changes

2021-08-18 11:02 UTC, glitch commented
@reuster986 if you get a chance can you check this one over?  It's for saving categoricals to HDF5.  The only real change is the addition of the `save` function to `categorical.py`.  Everything else is just whitespace cleanup, import cleanup, doc strings, or unit tests.

2021-08-19 19:23 UTC, reuster986 requested changes
@glitch the mechanics look good, but I would like the `load` API to auto-detect Categoricals, so that the user can round-trip DataFrames without having to explicitly call `ak.Categorical()`.

For example,

```python
df = {'int': ak.arange(5),
      'str': ak.array(['one', 'two', 'three', 'two', 'one']),
      'cat': ak.Categorical(ak.array(['a', 'b', 'c', 'b', 'a']))}
ak.save_all(df, path)
df2 = ak.load_all(path)
```

`df2` should be equivalent to `df` and should have column types `pdarray(int64)`, `Strings`, and `Categorical`. My thought in proposing the particular directory structure I did in #822 was that it would enable auto-detection of Categoricals vs. Strings via the filesystem. Alternatively, HDF5 group/dataset attributes could be used for this purpose, if that seems better.

2021-08-20 13:39 UTC, glitch commented
@reuster986 Sounds good 👍  Just a head's up I'm on vacation for a few days so it'll be a bit, but I'll ping you when the changes are ready.   Thanks for the feedback!

2021-08-20 14:59 UTC, reuster986 commented
@glitch enjoy your vacation!

2021-08-30 15:53 UTC, reuster986 approved these changes
looks great!

2021-08-30 15:53 UTC, merged