Closes #914 by handling case where the num_elements < num_locales
Bears-R-Us/arkouda pull request #934
Opened 2021-09-29 13:32 UTC by glitch

Closes #914 by handling case where the num_elements < num_locales
when saving to HDF5. When data is not present for a locale an
empty dataset is written to the file. These empty datasets get ignored
when reading back from disk.

Added unit tests for small numeric & strings arrays where we
expect the number of locales to be larger then the number of elements.

### Notes
1. Most of the changes for big blocks of code are white-space related because they were wrapped in if/else conditionals to handle boundary conditions.  It may be easier to view these sections in an ide or visual diff tool that can ignore whitespace changes (I like pycharm for this personally)
2. The fundamental change here is adding empty datasets to files on write when data does not exist on a locale and ignoring those on read.  This allows dataset / groups to be present in all files so no errors get thrown while reading back and the `alllow_errors` and `strictTypes` flags do not need to be toggled by the user (potentially masking other errors).

2021-09-29 14:09 UTC, ronawho commented
> may be easier to view these sections in an ide or visual diff tool that can ignore whitespace

FYI github supports this. In https://github.com/Bears-R-Us/arkouda/pull/934/files under the settings gear icon, or you can just do url hacking and add `?w=1`. e.g.  https://github.com/Bears-R-Us/arkouda/pull/934/files?w=1

2021-09-29 15:53 UTC, hokiegeek2 approved these changes

2021-09-29 15:53 UTC, hokiegeek2 commented on src/GenSymIO.chpl
> +            } else {
more chpldoc comments would be good in the else code block

2021-09-29 15:53 UTC, hokiegeek2 commented on src/GenSymIO.chpl
> +                    try! gsLogger.debug(getModuleName(),getRoutineName(),getLineNumber(),
recommend getting rid of try! as it can crash server

2021-09-29 16:02 UTC, reuster986 requested changes
General logic looks good, just a couple minor requests.

2021-10-01 18:51 UTC, reuster986 approved these changes

2021-10-04 17:59 UTC, merged

2021-10-05 12:57 UTC, ronawho commented on src/GenSymIO.chpl
> +    inline proc _isValidRange(r: domain(1)): bool {
Note that this is the same as `!r.isEmpty()` if you wanted to just use a builtin. In terms of terminology we don't tend to think of this as valid vs malformed, but just empty vs non-empty.